version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: 'postgres:latest'
    env_file:
      - postgressDatabase.env
    ports:
      - '5432:5432'

  mongodb:
    image: 'mongo:latest'
    hostname: mongodb
    ports:
      - '27017:27017'


